name: Perl CI with Inline::C and OpenMP

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        perl: ["5.40"]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - run: perl -V
      - run: perl -v

      - name: Install Required Perl Modules
        run: |
          cpanm --verbose --notest Module::Build Inline::C Alien::OpenMP \
                Util::H2O::More File::Temp Test::Exception Test::Deep \
                OpenMP::Environment File::ShareDir

      - name: Set Environment Variables for Shared Directory
        run: |
          export PERL5LIB=lib
          export PERL_LOCAL_LIB_ROOT=share
          export PERL_MB_OPT="--install_base share"
          export PERL_MM_OPT="INSTALL_BASE=share"
          echo "PERL5LIB=$PERL5LIB" >> $GITHUB_ENV
          echo "PERL_LOCAL_LIB_ROOT=$PERL_LOCAL_LIB_ROOT" >> $GITHUB_ENV
          echo "PERL_MB_OPT=$PERL_MB_OPT" >> $GITHUB_ENV
          echo "PERL_MM_OPT=$PERL_MM_OPT" >> $GITHUB_ENV
          cpanm --verbose .

      - name: Run Tests
        run: prove -v ./t
