name: Perl CI with Inline::C and OpenMP

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, debian-latest]  # Updated to include latest Debian
        perl: [system]  # Use the Perl that comes pre-installed
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ---- Install Build Essentials (Ubuntu & Debian) ----
      - name: Install Build Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgomp1 cpanminus
          sudo apt-get install -y libinline-c-perl libdist-zilla-perl  # Inline::C and Dist::Zilla

      # ---- Install Perl Modules via CPAN ----
      - name: Install Additional Perl Modules via CPAN
        run: |
          cpanm --verbose Alien::OpenMP Util::H2O::More File::Temp \
                 Test::Exception OpenMP::Environment File::ShareDir

      # ---- Install Author Dependencies ----
      - name: Install dzil authordeps
        run: |
          dzil authordeps --missing | cpanm --verbose  # Install required author dependencies
          cpanm --verbose Dist::Zilla::Plugin::VersionFromModule 
        
      # ---- Run `dzil test` ----
      - name: Run `dzil test`
        run: |
          dzil test
