name: Perl CI with Inline::C and OpenMP

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, rockylinux/latest]  # Ubuntu and RHEL-compatible Rocky Linux

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Essentials (Ubuntu)
        if: runner.os == 'Linux' && contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgomp1 cpanminus

      - name: Install Build Essentials (RHEL)
        if: runner.os == 'Linux' && contains(matrix.os, 'rockylinux')
        run: |
          sudo dnf install -y @development-tools gcc libgomp perl-App-cpanminus

      - name: Install and Test Perl Modules
        run: |
          cpanm --verbose --notest Inline::C Dist::Zilla Alien::OpenMP  # Install first without tests
          cpanm --verbose --force --test-only Inline::C Dist::Zilla Alien::OpenMP  # Run tests separately

      - name: Run `dzil test`
        run: |
          dzil test

